apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.6/manifests/install.yaml

images:
- name: quay.io/argoproj/argocd:v2.7.6
  newName: ghcr.io/flux-subsystem-argo/fsa/argocd
  newTag: v2.7.6-fl.15-main-52691a11

patches:
- path: config/remove-cm-argocd-cmd-params-cm.yaml

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  literals: # https://github.com/argoproj/argo-cd/blob/v2.7.6/docs/operator-manual/argocd-cmd-params-cm.yaml
  - server.insecure=false

