---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: podinfo-app-list

spec:
  generators:
  - list:
      elements:
      - k8sNamepace: ns1
        k8sUrl: https://kubernetes.default.svc
      - k8sNamepace: ns2
        k8sUrl: https://kubernetes.default.svc

  template:
    metadata:
      name: 'podinfo-{{k8sNamepace}}-argocd-list'
    spec:
      project: app-deploy
      source:
        repoURL: https://github.com/yashwanth-l/argo-deploy-feeder.git
        targetRevision: main
        path: deploy-kustomize-appset-list/argo-kind-k8s/podinfo
      destination:
        server: '{{k8sUrl}}'
        namespace: '{{k8sNamepace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2